# -*- coding: utf-8 -*-
"""kalkulator bangun-efti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8FvSuVtfVuhqOrqc3lwkegNl3_L7Aln
"""

import streamlit as st
from PIL import Image
import math

# ===== Data Bangun =====
bangun_data = {
    "Persegi": {
        "tipe": "datar",
        "gambar": "persegi.png",
        "input": ["Sisi"],
        "fungsi": lambda x: {
            "Ciri-ciri": "4 sisi sama panjang, 4 sudut siku-siku.",
            "Keliling": 4 * x[0],
            "Luas": x[0] ** 2
        }
    },
    "Lingkaran": {
        "tipe": "datar",
        "gambar": "lingkaran.png",
        "input": ["Jari-jari"],
        "fungsi": lambda x: {
            "Ciri-ciri": "Bentuk bundar sempurna, tidak memiliki sisi atau sudut.",
            "Keliling": round(2 * math.pi * x[0], 2),
            "Luas": round(math.pi * x[0] ** 2, 2)
        }
    },
    "Kubus": {
        "tipe": "ruang",
        "gambar": "kubus.png",
        "input": ["Sisi"],
        "fungsi": lambda x: {
            "Ciri-ciri": "6 sisi berbentuk persegi, 12 rusuk, 8 titik sudut.",
            "Volume": x[0] ** 3
        }
    },
    "Bola": {
        "tipe": "ruang",
        "gambar": "bola.png",
        "input": ["Jari-jari"],
        "fungsi": lambda x: {
            "Ciri-ciri": "Bentuk bulat sempurna, tidak memiliki rusuk dan sisi datar.",
            "Volume": round((4/3) * math.pi * x[0] ** 3, 2)
        }
    }
}

# ===== UI =====
st.title("🧮 Kalkulator Geometri Interaktif (Web)")

bangun = st.selectbox("Pilih Bangun Geometri:", list(bangun_data.keys()))

data = bangun_data[bangun]
st.subheader(f"{bangun} ({data['tipe'].capitalize()})")

# Tampilkan Gambar
try:
    img = Image.open(data["gambar"])
    st.image(img, width=250)
except FileNotFoundError:
    st.warning("Gambar tidak ditemukan.")

# Input Dinamis
nilai = []
for label in data["input"]:
    val = st.number_input(f"{label}:", min_value=0.0, step=1.0)
    nilai.append(val)

# Tombol Hitung
if st.button("Hitung"):
    try:
        hasil = data["fungsi"](nilai)
        st.success("Hasil Perhitungan:")
        for k, v in hasil.items():
            st.write(f"**{k}**: {v}")
    except:
        st.error("Terjadi kesalahan saat perhitungan.")